### ISSUE TITLE
Adding channel/email that already exists not handled 

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-services#6]
```
content_1    | { name: 'wilsonpage2', email: 'wilsonpage@me.com', tags: '' }
db_1         | ERROR:  duplicate key value violates unique constraint "channel_email_key"
db_1         | DETAIL:  Key (email)=(wilsonpage@me.com) already exists.
db_1         | STATEMENT:  insert into "channel" ("email", "name", "tags") values ($1, $2, $3)
content_1    | ::ffff:172.19.0.1 - - [14/Oct/2016:15:04:18 +0000] "POST /v1/channel HTTP/1.1" 500 1612 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
content_1    | TypeError: Cannot read property 'trim' of undefined
content_1    |     at module.exports (/usr/src/app/server/express/errorhandler.js:25:22)
content_1    |     at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
content_1    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:310:13)
content_1    |     at /usr/src/app/node_modules/express/lib/router/index.js:280:7
content_1    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
content_1    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:271:10)
content_1    |     at /usr/src/app/node_modules/express/lib/router/index.js:618:15
content_1    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:256:14)
content_1    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:121:14)
content_1    |     at handlerPromise.catch (/usr/src/app/server/express/promisehandler.js:10:9)
content_1    |     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
content_1    |     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:510:31)
content_1    |     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:567:18)
content_1    |     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:612:10)
content_1    |     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:687:18)
content_1    |     at Async._drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:138:16)
```

**Comment by samgiles** [comment]
Fixed in  da481f4.
